### ISSUE TITLE
compilation fails with intel compiler

### ISSUE THREAD

**Issue by pletzer** [WatershedModels/SWAT#2] opened 2022-03-02 21:45 UTC
ifort: command line remark #10148: option '-vec-report0' not supported
ifort: command line warning #10006: ignoring unknown option '-ffixed-line-length-80'
/nesi/nobackup/pletzera/swat/SWAT/src/modparm.f(77): error #6418: This name has already been assigned a data type.   [WOF_]
      real*8 :: sbactrop, sbactrolp, sbactsedp, sbactsedlp, ep_max, wof_lp
--------------------------------------------------------------------^
/nesi/nobackup/pletzera/swat/SWAT/src/modparm.f(83): error #6418: This name has already been assigned a data type.   [LYRTILE]
      real*8 :: snocovmx, snocov1, snocov2, rexp, rcor, lyrtile, lyrtilex
-----------------------------------------------------------------^
/nesi/nobackup/pletzera/swat/SWAT/src/modparm.f(338): error #6417: The dimensions of this array have been defined more than once.   [CH_S]
      real*8, dimension (:,:), allocatable :: dewpt,ch_w,ch_s,ch_n
---------------------------------------------------------^
…

**Comment by crazyzlj** [comment] 2022-03-06 14:38
Hi pletzer,
Thanks for your pull request.
Actually, after some investigation, I found the compilation error was caused by my mistakes in the [src/CMakeLists.txt](https://github.com/WatershedModels/SWAT/commit/61ec61a31992529633ab366f08a06f0139a9ee28#diff-148715d6ea0c0ea0a346af3f6bd610d010d490eca35ac6a9b408748f7ca9e3f4) which I fixed in the latest [commit](https://github.com/WatershedModels/SWAT/commit/61ec61a31992529633ab366f08a06f0139a9ee28).

Also, the length of line 193 in the [src/headout.f](https://github.com/WatershedModels/SWAT/commit/61ec61a31992529633ab366f08a06f0139a9ee28#diff-95aa88af9c0b2ab5d42044d8703be65fafcde8b0580d50dcd5f97de529986e39) that exceed 80 was truncated by an enter key.

I have also created two CIs hosted by Github Actions.
[![Build by GCC(gfortran) on Linux/macOS](https://github.com/WatershedModels/SWAT/actions/workflows/cmake_build_gcc.yml/badge.svg?branch=master)](https://github.com/WatershedModels/SWAT/actions/workflows/cmake_build_gcc.yml)
[![Build by IntelFortran(ifort) on Linux](https://github.com/WatershedModels/SWAT/actions/workflows/cmake_build_ifort.yml/badge.svg?branch=master)](https://github.com/WatershedModels/SWAT/actions/workflows/cmake_build_ifort.yml)

Please pull the latest code and test.

Hope this can help you.

**Closed by crazyzlj** 2022-03-06 14:38 UTC
